### ISSUE TITLE
FiraSans and FiraMono appear blank

### ISSUE THREAD

**Issue by gyscos** [google/fonts#10]
Similar to:
https://code.google.com/p/googlefontdirectory/issues/detail?id=368 and https://code.google.com/p/googlefontdirectory/issues/detail?id=407

Both the FiraSans and the FiraMono fonts appear buggy, since they only result in blank characters.

https://github.com/mozilla/Fira

**Comment by Gyscos** [comment]
FiraSans-Medium.ttf size from google/fonts:
158552 bytes

FiraSans-Medium.ttf size from mozilla/Fira:
401304 bytes

Other files have the same kind of disrepancy. Maybe a copy went wrong?

**Comment by codeman38** [comment]
mozilla/Fira is a newer version of the font with significantly more Unicode coverage and better line spacing. Should probably be updated here regardless.

**Comment by davelab6** [comment]
Yep 4.1 just came out so I'm due to do this soon!

**Comment by Mte90** [comment]
any news?

**Comment by Delapouite** [comment]
Same issue with this website using Fira Sans which is blank on my machine : http://firefox-dev.tools

**Comment by jkbyln** [comment]
Same issue only in IE9, in Windows Vista and 7 for me. Fira Sans displays blank.

**Comment by Mte90** [comment]
any news about this?

**Comment by jkbyln** [comment]
The version hosted by Mozilla doesn't have the rendering bug:
https://github.com/mozilla/Fira

**Comment by Schweinepriester** [comment]
Appears to be still buggy...

**Comment by Mte90** [comment]
any news??

**Comment by Gyscos** [comment]
If updating the font is not possible, maybe it could at least be removed from the repository so it doesn't conflict with the individual, valid font?

**Comment by davelab6** [comment]
I will update this; its tricky because I need to be careful about regressions. Also now Fira has so many styles, and I don't think I reached an agreement with the GF team on how to onboard them. Thanks for your patience.

**Comment by nekromoff** [comment]
Font still displayed as blank (whitespace)  in the latest Firefox 43.0.4.

**Comment by damiadev** [comment]
Failing with iceweasel 43.

**Comment by Mte90** [comment]
any news?

**Comment by krrg** [comment]
Is there an update on this?  This hasn't font hasn't been working for me for at least a year...(Fedora 22, Fedora 23, OpenSuse 13.2)

My two cents: either remove Fira from this repo, or use the version from https://github.com/mozilla/fira.  Is there any chance of an update on this situation?

**Comment by davelab6** [comment]
I've put https://github.com/google/fonts/compare/master...davelab6:ofl/firasans-v4.106g?expand=1 up and will check with Mozilla that its good to go

**Comment by davelab6** [comment]
Fixed in https://github.com/google/fonts/commit/79d9ee27365942aaa6cfd4576773999140fb0e5b

**Comment by enoch85** [comment]
@davelab6 When will the fix be released?

**Comment by davelab6** [comment]
I have a minor update to make and that going well it may go live on Wedneday

**Comment by davelab6** [comment]
I found that the vertical metrics shift in some browsers so I'll make another update this week, to go live next week.

**Comment by enoch85** [comment]
@davelab6 Any update here? Just updated to latest stable on Debian, still same issue.

**Comment by enoch85** [comment]
@davelab6 Thanks for your efforts on this, but it's been a month now since the last update here. What's going on?

**Comment by davelab6** [comment]
I've postponed working on this until I've finished working on new upcoming projects.

**Comment by enoch85** [comment]
@davelab6 Ok, thanks for the update. Do you have any ETA?

**Comment by bhulsman** [comment]
Found about this issue today; using Windows 7, fonts do not appear at all Chrome and some characters are missing in Internet Explorer 9.

**Comment by jace** [comment]
I've switched to using Fira Sans from Mozilla CDN until this is resolved. It's not anywhere as optimised at the Google Fonts version, but at least no rendering issues.

**Comment by LabLayers** [comment]
My client's site had a similar issue when browsing in Fedora Firefox 45.0.1 (no letters appearing at all) and Windows 7 Chrome 51.0.2693.2 dev (some letters missing) when loading Fira Sans from Google Fonts:

![image](https://cloud.githubusercontent.com/assets/607807/14271894/ac17c780-facb-11e5-9b86-9f1c1a3f5cda.png)

My issue was resolved when switching over to Mozilla's CDN but it would be nice to see this resolved sooner... rather than later... looking at you @google...

**Comment by mestaritonttu** [comment]
Was this fixed? I updated the package a few days ago and now I notice Fira Sans does not appear blank.

**Comment by enoch85** [comment]
No, this is **still not** fixed. Seriously Google....

Debain 8.3 Jessie (Deepin 15.01)
Chrome 50.0.2661.75 (64-bit)

**Comment by somepaulo** [comment]
Confirming. Issue persists.
With the font installed systemwide on my machine, calling it from Google displays font completely in FF, only regular weight in Chrome, and none at all in Tor, which is even more weird since it's just a modified FF. Using Mozilla CDN for now...

**Comment by LabLayers** [comment]
Any update on this? It's been 14 months since this issue was first raised and the I'm still experiencing problems using Fira Sans from Google Fonts on my end.

**Comment by enoch85** [comment]
ping @davelab6

**Comment by svivian** [comment]
I'm also having this issue... can't believe this has been going on for over a year now. The versions from the Mozilla CDN work perfectly, but they are 8x the file size of the Google Fonts versions (presumably because they don't use `unicode-range`).

I'm sure you're aware of the problem, but in case it helps, here is what Fira Sans looks like on Windows in (respectively) Chrome, Firefox, Internet Explorer 9, and at the bottom how the version from Mozilla CDN looks in Chrome.
 
![google-fonts-fira-sans](https://cloud.githubusercontent.com/assets/207887/16151443/f2d6e7e8-3494-11e6-933c-606bf3239a48.png)

**Comment by LabLayers** [comment]
Noticed some really bizzare behavior loading Fira Sans from Google Fonts in Safari on Mac OS Sierra DP1 - Apple seems load their Last Resort system fallback font for most characters even though other falback fonts are specified in the CSS. I understand this is prerelease software, BUT this is definitely NOT happening with other webfonts.

Here is a client site loading Fira Sans from Google Fonts:

![screen shot 2016-06-18 at 3 57 33 am](https://cloud.githubusercontent.com/assets/607807/16169785/428e4d70-3509-11e6-985f-e5acd9c911a0.png)

Here is the same client site loading Fira Sans from Mozilla's CDN (which unfortunately isn't well optimized or flexible) - which is used in production:

![screen shot 2016-06-18 at 4 10 42 am](https://cloud.githubusercontent.com/assets/607807/16169832/c6b73dcc-350a-11e6-973e-f50b3e9b6de6.png)

Heck, even Google fonts is screwed up.

![screen shot 2016-06-18 at 4 02 43 am](https://cloud.githubusercontent.com/assets/607807/16169790/96bcbefe-3509-11e6-887e-b45645061781.png)

Though other Google web Fonts seem to load fine  ```¯\_(ツ)_/¯```

![screen shot 2016-06-18 at 4 09 13 am](https://cloud.githubusercontent.com/assets/607807/16169824/81564854-350a-11e6-817a-3e0430cdb0c5.png)

I noticed that Mozilla is making an effort to get these fonts updated with mozilla/OpenDesign#74, but I would love to see this resolved sooner rather than later.

**Comment by enoch85** [comment]
@davelab6 Please prioritize this. Thank you!

**Comment by Mte90** [comment]
how many years we have to wait for fix this?

**Comment by ecoben** [comment]
We were unaware of these problems until we relaunched [DE-CIX.net](https://www.de-cix.net/). A fix for these problems would be greatly appreciated (and seems to be overdue - judging from the comments above). 

Any news on this?

**Comment by avian2** [comment]
I've been researching the problem with "Fira Sans Regular" rendering on Debian. See full report here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841293

That specific problem seems to be a complicated issue involving a specific WOFF2 file from Google, OpenType Sanitizer and libfreetype.

**Comment by MurzNN** [comment]
Maybe we can do temporary workaround for override this font locally on browser? Via way like http://www.makis.tv/wiki/override-helvetica-fonts-on-firefox-and-chrome.php
But seems this way not working for fonts, loaded from web via css :(

**Comment by MurzNN** [comment]
For workaround we can use another source for Fira Sans font, like this: `<link href='https://code.cdn.mozilla.net/fonts/fira.css' rel='stylesheet' type='text/css' />`

**Comment by enoch85** [comment]
@davelab6 Just to quote yourself:

> I've postponed working on this until I've finished working on new upcoming projects.

This was in March... Many new projects going on?

**Comment by chukkajazz** [comment]
I was having what sounds like a very similar issue with a different font - particularly that the render issues were occuring on Windows environments with Chrome and IE.

After much heartache, I re-formatted my font files online here: http://transfonter.org/

The key was the little 'Autohint' using ttfautohint option. All of a sudden things were rendering perfectly. Only downside is an increase in file size.

This might give a lead on how to properly address this issue though.

**Comment by Mte90** [comment]
I was annoying now I am very disappointed from this very low priority after all this comments.

**Comment by gonzalocasas** [comment]
Seriously, people? How come it's been 1.5 years since report and still no fix?

**Comment by m4rc1e** [comment]
@davelab6 Hey, I'll be tackling Fira this week.

We have a tonne of variants and weights here. I propose we do the following so the fonts are GF api friendly:

- Get rid of the two, four and eight family variants. These family variants are for the Hairline weights only.  They're like optical weights in printing. They add extra weight, depending on what size they're used. Imo, this is fiddly. A more elegant solution is to use variable fonts. If people object, I can include them.

- Remapping 
We have the following weights:
```
'FiraSans-Hair.ttf'
'FiraSans-Thin.ttf'
'FiraSans-UltraLight.ttf'
'FiraSans-ExtraLight.ttf'
'FiraSans-Light.ttf'
'FiraSans-Book.ttf'
'FiraSans-Regular.ttf'
'FiraSans-Medium.ttf'
'FiraSans-SemiBold.ttf'
'FiraSans-Bold.ttf'
'FiraSans-ExtraBold.ttf'
'FiraSans-Heavy.ttf'
'FiraSans-Ultra.ttf'
```

We should do this:
```
'FiraSans-Hair.ttf' -> 'FiraSansHairline-Regular.ttf'
'FiraSans-Thin.ttf' -> 'FiraSans-Thin.ttf'
'FiraSans-ExtraLight.ttf' -> 'FiraSans-ExtraLight.ttf'
'FiraSans-Light.ttf' -> 'FiraSans-Light.ttf'
'FiraSans-Regular.ttf' -> 'FiraSans-Regular.ttf'
'FiraSans-Medium.ttf' -> 'FiraSans-Medium.ttf'
'FiraSans-SemiBold.ttf' -> 'FiraSans-SemiBold.ttf'
'FiraSans-Bold.ttf' -> 'FiraSans-Bold.ttf'
'FiraSans-ExtraBold.ttf' -> 'FiraSans-ExtraBold.ttf'
'FiraSans-Heavy.ttf' -> 'FiraSans-Black.ttf'
'FiraSans-Ultra.ttf' -> 'FiraSansUltra-Regular.ttf'


Weights removed: Book, Ultra Light,
Weights renamed: Hair, Heavy, Ultra
```

@davelab6 @patrykdesign What are your thoughts on this?

I was very happy with the Mono fonts. Also, the otf folder includes condensed fonts. They're not present in the ttf folder.

**Comment by patrykdesign** [comment]
@m4rc1e Hey, yes some of the weights are experimental. So the mapping should go as follows for CSS weighting...

- Thin (22em / CSS 100)
- UltraLight (34em / CSS 200)
- ExtraLight (46em / CSS 250)
- Light (58em / CSS 300)
- Book (84em / CSS 350)
- Regular (92em / CSS 400)
- Medium (128em / CSS 500)
- SemiBold (142em / CSS 600)
- Bold (158em / CSS 700)
- ExtraBold (178em / CSS 800)
- Heavy (198em / CSS 900)

Also please make sure you're using the latest version, 4.2 was recently released: https://github.com/carrois/Fira/tree/master/Fira_Sans_4_2/Fonts/FiraSans_OTF_4203

And I believe we moved off TTF since OFT supports advanced type features present in Fira. So hopefully you can use the OFTs instead. Thanks for your hard work.

**Comment by m4rc1e** [comment]
Hey,

Thank you for your in depth response. I will make sure we use the latest release.
We need to use the following mapping for our api to work correctly:

```
"Thin": 250,
"ExtraLight": 275,
"Light": 300,
"Regular": 400,
"Medium": 500,
"SemiBold": 600,
"Bold": 700,
"ExtraBold": 800,
"Black": 900
```

At the moment, we only support ttfs I'm afraid. I'm guessing you folks used the otf format because you can use floating point units. This is especially useful in the hairline weight. ttfs uses integers only.

I hope you understand and don't mind us using ttfs instead?

Cheers,
Marc

**Comment by patrykdesign** [comment]
@carrois should be able to provide the TTF exports, hopefully he'll have some cycles to do so soonish.

**Comment by patrykdesign** [comment]
@m4rc1e hey as far as the mapping goes, I think for maximum I'll remap THIN from CSS 100 to 250 and Ultralight from CSS200 to 275 while keeping the other weights the same as their CSS mapping spec: 

- Light (58em / CSS 300)
- Regular (92em / CSS 400)
- Medium (128em / CSS 500)
- SemiBold (142em / CSS 600)
- Bold (158em / CSS 700)
- ExtraBold (178em / CSS 800)
- Heavy (198em / CSS 900)

**Comment by m4rc1e** [comment]
@patrykdesign please don't worry about any of this :-). I have it all automated. Please do not deviate from your sources to please us. You don't want to upset your existing users. We can modify our own version of the fonts for our spec. I've been doing this for [Lato](https://github.com/googlefonts/LatoGFVersion)

We have [fontbakery](https://github.com/googlefonts/fontbakery) which helps us to hot fix fonts to work with our spec.

**Comment by m4rc1e** [comment]
Thank you for the confirmation.

I'll look into the conversion. It is possible.

Cheers,
Marc

**Comment by m4rc1e** [comment]
Almost finished mastering the v4.2 fonts so they'll work on GF.

![screen shot 2016-11-29 at 10 33 12](https://cloud.githubusercontent.com/assets/7525512/20704388/6147cf1a-b61f-11e6-9a9f-0a264034f2e0.png)

Issue has been solved.

**Comment by ben-rabid** [comment]
@m4rc1e thanks so much for fixing this. It came up this week with a client website and brought me here. 

I've asked them to hold until the fix is out rather than change their site font. Do you have an ETA for when v4.2 might land?

**Comment by m4rc1e** [comment]
@davelab6 shall I submit a pr for this?

Our hotfix repo is [here](https://github.com/googlefonts/FiraGFVersion). If you urgently need these fonts, self host the fonts in the /fonts directory.

**Comment by carrois** [comment]
> @carrois should be able to provide the TTF exports, hopefully he'll have some cycles to do so soonish.

@patrykdesign not sure what you mean. 4203 TTF files are all there?!

**Comment by m4rc1e** [comment]
@carrois When I look at the official repo's ttf [folder](https://github.com/mozilla/Fira/tree/master/ttf), there are no Condensed weights. @patrykdesign's [link](https://github.com/carrois/Fira/tree/master/Fira_Sans_4_2/Fonts/FiraSans_OTF_4203) includes both Condensed and Compressed variants. My hotfix repo includes those Condensed and Compressed variants. Is the link @patrykdesign valid? or should I just hotfix the official repo sources only?

Cheers,
Marc

**Comment by carrois** [comment]
Yes the link is valid and in case of doubts the most recent. We only have control over this repository, not over Mozilla's.

**Comment by patrykdesign** [comment]
@carrois my bad didn't see that the TTFs were in the web version [https://github.com/carrois/Fira/tree/master/Fira_Sans_4_2/Fonts/FiraSans_WEB_4203](url)

@m4rc1e please use the carrois repo ^^^, we're still trying to figure out what Mozilla intends to do with the project since I left and Firefox OS was cancelled.

**Comment by carrois** [comment]
Ok, then everything seems to be clarified.

@patrykdesign We're curious ;-)

**Comment by davelab6** [comment]
Sorry to hear that. Google Fonts can adopt the project if Mozilla would like

**Comment by patrykdesign** [comment]
@davelab6 @carrois great to hear, I'll let them know. They just need to elect a new champion at the company to drive some sort of roadmap, so they are deciding on that now.

**Comment by davelab6** [comment]
@carrois @patrykdesign alas I am going to need to change the names of the widths in the family names to meet the GF requirements. I'll follow up shortly with this

**Comment by enoch85** [comment]
Is this patched yet? Still not working on Debian.

**Comment by m4rc1e** [comment]
@enoch85 version served on fonts.google.com is v3.107. Our update is 3.206. I guess we didn't upload because we need sort out the widths naming first.

**Comment by enoch85** [comment]
@m4rc1e Thanks for the clarification.

**Comment by Sprinkles22** [comment]
Just doing a little research as this font is rendering fine for me EXCEPT when I have an 'f' and 'i' next to eachother. What gives? Been using the Google Font version, should I download from here or Mozilla to fix or will this be fixed shortly?

**Comment by m4rc1e** [comment]
@Sprinkles22 add a screenshot.

Also, which platform and browser?

**Comment by enoch85** [comment]
This issue is finally fixed for me on Chromium! Thanks guys!

`Version 55.0.2883.75 built on Debian stretch/sid, running on Debian 8.0 (64-bit)`

**Comment by svivian** [comment]
Just checked this out again and using Fira Sans from Google Fonts no longer has the problems I showed [earlier](https://github.com/google/fonts/issues/10#issuecomment-226764897). It displays fine in IE9 as well as Chrome/Firefox.

**Comment by gyscos** [comment]
Looks fixed! And it only took 2 years :)

**Comment by davelab6** [comment]
Thank you for your patience :)

**Comment by ben-rabid** [comment]
:clap: thank you!

**Comment by gonzalocasas** [comment]
thank you, folks!

**Comment by c9mbundy** [comment]
Fira+Sans only appears to load 400-regular for me.

The loaded webfont stylesheet only lists 400-regular, and other sizes are not available to the css.

Other fonts (e.g. Nunito+Sans) no problem, but Fira+Sans only 400-regular
