### ISSUE TITLE
Rubik font not work

### ISSUE THREAD

**Issue by Uzumachi02** [google/fonts#1137]
http://prntscr.com/g91vkr
https://fonts.google.com/specimen/Rubik

**Comment by al5dy** [comment]
The font does not work only on Windows systems!!!

**Comment by Findus23** [comment]
I am having the same issue in chromium and firefox on Linux (Debian)

**Comment by m4rc1e** [comment]
Here's a js bin test: http://jsbin.com/fozodeliru/edit?html,output

Can confirm this issue is present in IE browsers.

![screen shot 2017-08-16 at 09 41 46](https://user-images.githubusercontent.com/7525512/29355086-8dea96e6-8267-11e7-9c79-65ceaf316d0a.png)

**Comment by Findus23** [comment]
I have tested a bit more and it seems like the issue only occurs on Windows 7 and on my PC running Debian:

Win 7:
 - Internet Explorer 11: doesn't work
 - Firefox : works
 - Chrome: doesn't work

Windows 10:
 - Chrome: works
 - Firefox: works
 - Internet Explorer 11: works
 - Edge: works

MacOS:
 - Safari: works

Debian (KDE):
 - Chromium: doesn't works
 - Firefox (ESR): doesn't work

**Comment by jessmchung** [comment]
We've found:

RHEL7:
* Chrome v60 (stable) doesn't work
* Chrome V61 (beta) doesn't work

Windows 8:
* Chrome doesn't work

**Comment by yamikuronue** [comment]
We're seeing the outage on various machines in different browsers, depending on the browser caching settings. My coworker and I have identical machines, and he can see the font while I can't. This is Windows 10 on Chrome; he doesn't see the font in Firefox, despite seeing it in Chrome.

**Comment by suakang** [comment]
I'm also having the issue where Rubik renders white/blank on Windows 7 and 8 with Chrome and Firefox.

**Comment by davelab6** [comment]
@m4rc1e found a way to autodetect the problem (using @hintak's https://github.com/HinTak/Font-Validator) so this one shouldn't happen again; and overall says Mac OS X's Quartz and Windows' DirectWrite are fine, but older rasterizers and freetype are not.

**Comment by davelab6** [comment]
The update is being rolled bac

**Comment by LorandBiro** [comment]
Any update on the rollback?

**Comment by nlessmann** [comment]
Works again for me

**Comment by davelab6** [comment]
Rollback is complete. (With a rollback, the css is cached for 24 hours, so if someone saw the buggy font, will they continue to see it until they clear their cache (eg, force refresh on a page with the css) or until it expires in 24 hours)

**Comment by Uzumachi02** [comment]
works, thanks

**Comment by HinTak** [comment]
Does anybody still have a copy of the broken version of the font? I get a bit confused as I where the rollback, etc are logged. changes in https://github.com/google/fonts/tree/master/ofl/rubik does not seems to talk about rollback of any sort.

**Comment by davelab6** [comment]
@HinTak actually this repo hasn't had the rollback, that's right. I should fix that.

**Comment by HinTak** [comment]
@davelab6 : yes, the fonts in the public repo (committed on 7th August) are still broken  - I assume the rollback happened in some google private repo. FYI, the errors from the legacy Microsoft 1.0 backend is:

```
E	| E6016	| FDEF out of range
		Size 4, FDEF, Pre-Program, At ByteOffset 3646, 
A	| A6000	| An exception occurred during rasterization testing
		Secure Rasterizer error: Function out of range   at Avalon.Media.Text.TrueType.RasterInterf.RenderSize(...
```

And the error from FontVal 2.1 is: 

```
I	| I6070	| Supplementary Information
		Glyph 0 at size 4
A	| A6000	| An exception occurred during rasterization testing
		FreeType error: Stack overflow.  at SharpFont.Face.LoadGlyph
```

I believe FontVal 2.0 would show only the A6000 message. The additional I6070 message (about where the fatal error happens) was introduced in 2.1 . 

In both cases, A6000 indicates a fatal problem where either the Microsoft engine or FreeType cannot cope. Glyph 0 (i.e. the first glyph) in the 2nd case, means about the same thing as "Pre-Program". So the behavior between the Microsoft backend and the FreeType backend is really whether the problem was spotted at the end of prep, or the beginning of glyf (they follow each other in loading). FreeType is in general a bit lazier, so that's not surprising.

I could change the code slightly so that "E6046 = Stack Underflow" is emitted; but A6000 seems more appropriate since the font is clearly broken.

**Comment by HinTak** [comment]
FYI, `Avalon.Media.Text.TrueType...` seems to be Microsoft's codename for Presentation Foundation:

https://en.wikipedia.org/wiki/Windows_Presentation_Foundation

**Comment by davelab6** [comment]
I've asked @laerm0 to resolve the hinting on this and prepare a new release, and then @m4rc1e to review and make a new PR. Micah and Marc discussed this at ATypI in Montreal last month. 

Micah:

> the issue was you merged old Rubik and new Rubik and forgot to compile and ship in VTT? Why did you [Marc] merge the two? Did you just merge in my hand-hinted Hebrew into the old stuff? Because I did the same when I sent you the Hebrew...

Marc:

> Partly. I forgot to ship the fonts in VTT and I never ran them through cacheTT.
>
> The problem is larger than that I'm afraid. While you were hinting Rubik, Alexei was busy making changes. In a VTT workflow, this is a big no no. I guess he never read my email or didn't understand the implications. I tried to work around this in the failed release by writing a glyph swap script.
>
> I think the first step will be to rehint the glyphs Alexei modified. Dave are you cool with this?
> 
> If rehinting the modified glyphs is approved. I will need to transfer the existing good hints.

Micah: 

> Ah, gotcha. That's all doable. If Dave says so, I'll just rehint the new stuff Alexei added. 
>
> What do you mean you need to transfer the existing good hints? I still have my original source and some versioning even, so I can just import the new glyphs into what I have that works.

Marc:

> Forgive my ignorance, it has been years since I've used VTT. I'm guessing the new version can now import hints?
>
> In the past, you could only replace glyphs from another font.

Micah:

> It can import hinted glyphs and attempt to make the fpgm and prep match; I meant more that I can just import the unhinted new stuff from Alexei and hint it. I was wondering what you were merging.

Marc

> This approach will just overwrite Alexei's modified glyphs with the older hinted glyphs. IMO, this is not importing hints but changing the whole glyph. We don't want this.
>
> I wrote a script a while back to import VTT hints. I will ask my old boss if we can liberate this or just use it as a one off.

Micah

> No, I'd see which glyphs from Alexei are new and then import those (they're not hinted yet) and then hint them.

**Comment by laerm0** [comment]
When I hinted Rubik, I sent my hint source. Which repo are the files I sent you in? I wanted to diff them with what I have in my archives.

**Comment by m4rc1e** [comment]
You'll find everything you need in the upstream repo, https://github.com/googlefonts/rubik

**Comment by laerm0** [comment]
Great, thanks.

**Comment by ngdio** [comment]
How has this still not been fixed after over a year?

**Comment by HandHugs** [comment]
This is STILL happening for us. RUbik 300 weight is not displaying on multiple browsers -- even multiple devices.

**Comment by esedic** [comment]
I just received a feedback, Rubik font is not rendering on Windows 7 machines.

**Comment by esedic** [comment]
Update: I my case the problem on Windows 7 was because of the font was loaded locally. when it was switched to Google servers, font appeared again.

**Comment by fireattack** [comment]
As far as I can tell, the version currently shows on [Google Fonts](https://fonts.google.com/specimen/Rubik) works fine on Win 7.

But there are some distributors are still using old/broken versions, such as [Adobe Fonts](https://fonts.adobe.com/fonts/rubik).

SO questions are: 

1. Should we close this issue as it should have been solved?
2. Is there a way to notify distributor to update their fonts, hopefully from Google team directly?

**Comment by RubenKelevra** [comment]
The AUR-package for ArchLinux which builds from git, still reverts a commit based on this bug.

Is it safe to remove the revert?

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-google-fonts-git

**Comment by Collectonian** [comment]
August 2020, this is still an issue.  Works fine in Windows 10, but not on Windows 7.

Site I try to view with Rubik via Google Fonts:
![image](https://user-images.githubusercontent.com/60377061/90295651-256e7500-de4f-11ea-90a8-0452ae68c564.png)

Same site if I just use the web developer toolbar and disable the Rubik declaration
![image](https://user-images.githubusercontent.com/60377061/90295810-8bf39300-de4f-11ea-8cea-df82bbd6c5d1.png)

The font itself displays perfectly fine on the Google Fonts page.  I had the font installed locally so deleted it.  No change.  Reinstalled the newest one.  Same.  Cleared cache on both browsers, still nothing.  

This has consistently been the issue when I encounter a site looking like the one above.  Go to the web developer toolbar, check the style, see Rubik, disable, all good.

**Comment by xosofox** [comment]
> August 2020, this is still an issue. Works fine in Windows 10, but not on Windows 7.

July 2021, this is still an issue. Works fine in Windows 10, but not on Windows 7.

So, we agree? **DO NOT USE RUBIK**

**Comment by mattmagi** [comment]
Not loading for me on various window devices as well as google search on android.

**Comment by peterflynn** [comment]
For anyone who needs a workaround on Win 7/8 for a website where all the text is invisible due to this bug... (in Chrome):

* First resort: if the font is inherited from somewhere global like a CSS rule for `body`, just uncheck the `font-family` in the Elements tab > Styles sidebar and you should be good to go.
* If it's defined all over the place in many different CSS rules, you can force the webfont download to fail. Open the "Network Request Blocking" panel (under "..." > More tools), click Add Pattern, and put in "rubik" - or ".woff" to block _all_ webfont downloads for this page. Then in the Network tab, tick "Disable cache" and reload the page while Dev Tools is still open.

**Comment by HinTak** [comment]
Yes, it is still broken, and interestingly enough, current fedora is shipping the broken version, apparently 2.100 from a 20200314 snapshot.

Revisiting some of issues where freetype behaves differently from past/present MS rasterizer.

**Comment by harnishdesign** [comment]
Bold behavior not working in **FireFox (108.0.2 (64-bit) )** browser. How can i fixed this ? 
Please check below screenshot of browser.

### FireFox:
![firefox](https://user-images.githubusercontent.com/2634085/211565776-a6837e46-44ca-4fff-aa63-8246ef3242f8.jpg)

### Google Chrome:
![chrome](https://user-images.githubusercontent.com/2634085/211565825-9c4c49be-07a0-4f01-9e79-f06ddb27ddd1.jpg)
