### ISSUE TITLE
Roboto Thin not showing in Inkscape or the GIMP

### ISSUE THREAD

**Issue by ResetOnset** [google/fonts#137]
I downloaded the Roboto fonts from Google fonts today to ensure I had the latest versions. They are TTF files (am I dreaming or have I seen reference to an OTF version?). 

The Thin weight is not showing in Inkscape nor GIMP (typically, the weight I want to use!) but strangely it is showing in LibreOffice Writer.

Any ideas? Thanks

**Comment by ResetOnset** [comment]
Update: I deleted all weights apart from Thin in my .fonts folder (I'm using Debian Wheezy) and the Thin weight did show up in Inkscape, **but it was listed as Light**! 
Trouble is I need both Thin and Light for a project I'm working on...

**Comment by Stadly** [comment]
I'm also experiencing this issue :(

**Comment by fitojb** [comment]
I would file this issue against Inkscape (which is the application actually having this issue), not this repo.

**Comment by Stadly** [comment]
I've created a bug report [here](https://bugs.launchpad.net/inkscape/+bug/1555109).

If you experience this issue, please go to the bug report and subscribe to notifications and mark the bug as also affecting you to increase the heat of the bug.

**Comment by davelab6** [comment]
@m4rc1e will https://github.com/google/roboto/issues/236 fix this?

**Comment by m4rc1e** [comment]
@davelab6 this seems to be a common problem with GIMP and Inkscape, https://github.com/google/fonts/issues/633

We haven't had any reports using other apps.

**Comment by davelab6** [comment]
https://twitter.com/sovtsov_egor/status/839890784438513664 reports an issue with Roboto Condensed Regular appearing as Roboto; I assume in Chrome when the fonts are installed locally. Would be good to confirm that is fixed when Roboto is updated.

**Comment by laerm0** [comment]
By way of trivial update, the Inkscape issue is still not fixed.

**Comment by EminoMeneko** [comment]
I just noticed that while trying to use Google Fonts in Inkscape on Windows 10. Fonts were installed using skyfont which means the fonts are primarily installed in a specific folder. Fonts are recognized by Windows Explorer. They have a proper TTF extension. So I chose them all and installed them using the right click option. Then I chose Windows Fonts folder and tried to look for some specific fonts. They were in the folder. Restarted Inkscape but no luck.

**Comment by brezal** [comment]
Any updates here? I'm experiencing this as well.

**Comment by FarrukhShahidAC** [comment]
I found the solution to this problem.

All you have to do is
go to edit > preferences
Then on the left list view go to Folders and select Fonts
Here you have to add the folder which contains the Roboto Fonts

And you are done :)

**Comment by ResetOnset** [comment]
Thanks Farrukh. I added my /home/user/.fonts folder as suggested, and Roboto Thin seems to working now.  I'm surprised that a program like GIMP doesn't automatically include a standard font folder.

**Comment by Stadly** [comment]
I cannot find "Folders" in the Preferences window. Is it not there on Windows?

![image](https://user-images.githubusercontent.com/7263579/69234866-77b88900-0b90-11ea-9371-074bcfe05b48.png)

**Comment by FarrukhShahidAC** [comment]
> I cannot find "Folders" in the Preferences window. Is it not there on Windows?
> 
> ![image](https://user-images.githubusercontent.com/7263579/69234866-77b88900-0b90-11ea-9371-074bcfe05b48.png)

Yes, it will be different in windows. Unfortunately, cant address your problem as I don't have such OS
But I would recommend you to use Photoshop in the windows.

**Comment by EminoMeneko** [comment]
I'm using Windows and to me that issue is old already. I got this to work but I do not remember what or how I did. That said, I think itwas something such as installing font as admin.
Regards.
![image](https://user-images.githubusercontent.com/1531281/69263694-1ad7c580-0bc6-11ea-87c1-025a99cf4bc3.png)

**Comment by Stadly** [comment]
Right-clicking the font files and choosing `Install for all users` instead of `Install` helped! I'm still not able to use all font variants, but at least I can use the normal one.

**Comment by FarrukhShahidAC** [comment]
> Right-clicking the font files and choosing `Install for all users` instead of `Install` helped! I'm still not able to use all font variants, but at least I can use the normal one.

If you have to use all variants, you have to download them explicitly https://fonts.google.com/?selection.family=Roboto 
Click add button beside the font tab a window will open, then clicking that window you will see 2 tabs (Embed, Customize) 
Click customize and check the variants you want to use

**Comment by pedromarqueslx** [comment]
> 
> 
> I'm using Windows and to me that issue is old already. I got this to work but I do not remember what or how I did. That said, I think itwas something such as installing font as admin.
> Regards.
> ![image](https://user-images.githubusercontent.com/1531281/69263694-1ad7c580-0bc6-11ea-87c1-025a99cf4bc3.png)

Instal font for all users....

**Comment by drmrbrewer** [comment]
Selecting `Install for all users` rather than just `Install` worked for me (Inkscape).
