### ISSUE TITLE
Raleway 400 Normal is now ultra bold since 12/15/15

### ISSUE THREAD

**Issue by MollyWeb** [google/fonts#163]
Raleway 400 Normal font weight has changed to ultra bold. I have to temporarily change font-weight from 400 to 500 to get it back looking like a "normal" weight. Is this intentional? 

https://www.google.com/fonts/specimen/Raleway

**Comment by davelab6** [comment]
Nothing changed here, Uninstall the fonts and you'll no longer see this

**Comment by jordanlewin** [comment]
Having this issue as well, a year later. Raleway 400 (normal) shows up as ultra bold in multiple browsers. However, the fonts are not "installed" anywhere, as they are being served directly from Google Fonts servers. How do I address this issue and "uninstall" the fonts in this case? I've cleared browser cache and that hasn't fixed the issue. Thanks!

**Comment by gwlove** [comment]
I'm facing the same thing without a fix, both on our website and in google docs.

**Comment by cjsinnbeck** [comment]
I have the same problem - could not figure out where I changed the font-weight in my CSS, and now I'm 99.9% sure that I actually have not changed it, since it was an older project that I have not touched for some time. In my case, weight=300 now looks like weight=400 in Chrome as well as Safari.

**Comment by cjsinnbeck** [comment]
I found sort of a workaround to this. If I include Raleway in only 300 and 700, 700 will be used for bold and 300 for normal. They are clearly distinguishable. 

<link href="https://fonts.googleapis.com/css?family=Raleway:300,700" rel="stylesheet">

If I do not specify weights (or specify 300 and 400), it comes out looking like 400 all of it. It seems to me that the browser will select 400 for both "normal" and "bold" in this case. I might be wrong, but I am nevertheless sure that this was not a problem 2-3 months ago, so maybe Google Fonts is serving up the font CSS file in a different manner that earlier.

**Comment by gwlove** [comment]
Thank you! I just made the change to 300. Had to change a few CSS files too but the website is looking back to normal. Raleway in google docs is still wonky

**Comment by cjsinnbeck** [comment]
@gwlove You're welcome. Maybe we have to change it back if the font returns to its previous state, but let's see.

**Comment by m4rc1e** [comment]
I released an update to Raleway quite a while back. The version which is currently being hosted on fonts.google.com, does not have this issue. Here's a test [jsbin](http://jsbin.com/qiyayopozi/edit?html,output)

![screen shot 2017-06-13 at 11 46 20](https://user-images.githubusercontent.com/7525512/27079041-12a6eef0-502e-11e7-9daa-5a252613e073.png)

**Comment by filionalain** [comment]
Still have the issue, here's your jsbin from Chrome : 
![image](https://user-images.githubusercontent.com/29968854/27943010-aced73fc-62a9-11e7-9d0b-737a3623921d.png)

**Comment by m4rc1e** [comment]
@filionalain have you got the old family installed locally?

**Comment by filionalain** [comment]
I did have the Raleway extra bold installed, it is fine when I uninstall the font. Thanks!

**Comment by laerm0** [comment]
This issue appears to be solved so I will close it.

**Comment by petrorington** [comment]
@filionalain When you say to uninstall the font, what does it mean?
I'm using the webfont from fonts.google.com with @import statement. Can you please explain how you uninstalled the font?

**Comment by alexplusde** [comment]
> @filionalain When you say to uninstall the font, what does it mean?

by deleting it locally from the file system / operating system fonts folder.
