### ISSUE TITLE
Open quote character in Neuton 300 is wrong

### ISSUE THREAD

**Issue by tomcritchlow** [google/fonts#17]
When typing the character “ in Neuton 300 it misaligns with the next character as you can see in the following screenshot:

![screen shot 2015-04-19 at 7 05 01 pm](https://cloud.githubusercontent.com/assets/474894/7221762/0193b33c-e6c7-11e4-9d03-40e55f54c204.png)

**Comment by adrientetar** [comment]
cc @anoxic

**Comment by anoxic** [comment]
This has been corrected on the [latest release](http://www.impallari.com/projects/update/25), but for some reason that hasn't been pushed out on Google.

**Comment by tomcritchlow** [comment]
Hello - any update on when this might get fixed? I'm not familiar with how often this project is updated or maintained but I'm actively using this font and would love for a fix for this. Thanks

**Comment by anoxic** [comment]
@tomcritchlow If you get or generate the webfont from Fontsquirrel this is already fixed. I would recommended going down that route until the Google hosted version is updated.

**Comment by tomcritchlow** [comment]
Unfortunately this issue still persits on fontsquirrel too:

See this:

![image](https://cloud.githubusercontent.com/assets/474894/12071692/0c2ac382-b087-11e5-9127-c84503266e37.png)

Vs this:

![image](https://cloud.githubusercontent.com/assets/474894/12071694/1649c8a4-b087-11e5-857b-50aaf75c4471.png)

**Comment by tomcritchlow** [comment]
Ok - for anyone following along at home, as per the original comment the source has been updated here: http://www.impallari.com/projects/update/25 and you can download that and then generate your own webfont from it using fontsquirrel (but not using the neuton files available for download at fontsquirrel).

Thanks

**Comment by m4rc1e** [comment]
Closing, LGTM.

Updated in #440 

![screen shot 2017-06-14 at 14 00 33](https://user-images.githubusercontent.com/7525512/27133414-e425a684-5109-11e7-9ad1-5339b027e1cb.png)
http://jsbin.com/nepayowoci/edit?html
