### ISSUE TITLE
Add Box Drawing block to Source Code Pro

### ISSUE THREAD

**Issue by smasher164** [google/fonts#2465]
Box Drawing characters are not rendered correctly for Source Code Pro, when using `fonts.googleapis.com` for hosting. See https://github.com/golang/go/issues/38763, which encounters this issue when displaying documentation on pkg.go.dev. The stylesheet used for its `@font-face` definitions is https://fonts.googleapis.com/css?family=Work+Sans:600|Roboto:400,700|Source+Code+Pro.

Please consider adding the `unicode-range: U+2500-257F;` to  a `@font-face` directive for Source Code Pro. This may warrant another subset added to the metadata, like `subsets: "box-drawing"`.

**Comment by smasher164** [comment]
Closing since downstream issue has been resolved.

**Comment by t-kalinowski** [comment]
I think this is still unresolved: AFAIK this was just worked around by golang/go. The `@font-face` def still does not contain unicode ranges for box drawing characters.
