### ISSUE TITLE
Crimson Text no longer available

### ISSUE THREAD

**Issue by RELeyland** [google/fonts#4125]
HEllo - i'm using crimson text in an app and it appears it is no longer available https://fonts.google.com/specimen/Crimson+Text?family=PT+Sans

Are you able to say if this is permanent or just a temporary issue?

Thank you!

**Comment by RosaWagner** [comment]
You can use Crimson Pro :)

**Comment by RELeyland** [comment]
thank you for the quick response. We had seen crimson pro as an option. Can I check though, is there a risk at this font, or any other suddenly being removed from the googlefonts database? Is there ever a way of knowing when fonts might stop being available so that we are able to plan around this kind of thing happening again?

**Comment by RosaWagner** [comment]
The font is hidden from the platform because it has a lot of bugs that are fixed in the "Pro" version. Websites that are using it through the API are still served with it (so no existing websites are broken, trust is intact). So the font is not completely removed, it is hidden to push users to use a version with less bugs and of better quality (technically speaking). Moreover, if one really needs it, it is still available in this repository, and in the designer's repository: https://github.com/skosch/Crimson.

But yes, we take your request into consideration to re-add the font since other users have also made the demand. But it would force us to update it to fix the bugs… which we already did… in the pro version. Let's see if we can find a solution, in any case, it won't happen in the next days ;)

Curiosity, why would you choose the Text version over the Pro version?

**Comment by RELeyland** [comment]
Hi,

We are happy to use pro - it makes sense. I'm mainly asking as we use google fonts a lot on our platform. Text that is styled with Crimson Text is still showing however if we make any edits this is lost, I'll update this particular app to make sure everything uses pro now. I'm really asking as the platform I work for is a CMS that helps organizations create and publish web apps. Content is edited a lot of the time so I've noticed that if I try to edit text that previously used Crimson Text, this styling is now lost when I go to make updates. This is not the end of the world if it only occasionally happens, we just haven't experienced this before.

**Comment by RELeyland** [comment]
and sorry I should say - we use google fonts a lot!

**Comment by davelab6** [comment]
@RELeyland you should be able to hard code it to be always present in your family list, so it keeps working for you
