### ISSUE TITLE
Google Fonts website won't load if the browser uses Lithuanian locale

### ISSUE THREAD

**Issue by rimas-kudelis** [google/fonts#4682]
#This issue also works for requesting features. 

**Describe the issue**

For a while now, I've been experiencing a weird issue: navigating to fonts.google.com would show me the UI for a split second, and then switch to a "Something went wrong. Please try again soon." error with a random emote. I tried accessing it from both Firefox and Chromium, to no avail.

Looking at the Network console in Firefox, I see one failed request there: the one which tries to load Roboto Flex from `https://fonts.googleapis.com/css2?family=Roboto%20Flex:ital,opsz,slnt,wdth,wght,GRAD,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,XTRA@0,8..144,0,100,400,0,79,750,-203,738,514,712,468&directory=3&subset=latin&display=block&text=%20,.Aabdefghiklmnorstuw`. The server returns a 400 error to this request, and after it fails, there appear several errors in the Javascript console.

The error page there contains the following error message:
```
Axes must be listed alphabetically (e.g. a,b,c,A,B,C)

Roboto Flex:ital,opsz,slnt,wdth,wght,GRAD,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,XTRA@0,8..144,0,100,400,0,79,750,-203,738,514,712,468
                                                                            ^
```

The stylesheet loads successfully if I access it via this URL instead: `https://fonts.googleapis.com/css2?family=Roboto Flex:ital,opsz,slnt,wdth,wght,GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC@0,8..144,0,100,400,0,79,750,-203,738,514,712&directory=3&subset=latin&display=block&text= ,.Aabdefghiklmnorstuw`.

Apparently, the "Axes" were sorted not in the order the Google server expected them, and this is because in my case, Lithuanian collation (which matches my browser locale) was used, which, unlike English, orders `Y` right after `I` instead of at the end of the alphabet. After changing browser locale to English, I can navigate to fonts.google.com successfully.

**To Reproduce**
Run Chrome or Firefox in Lithuanian locale and navigate to fonts.google.com – you'll see an error.
Run Chrome or Firefox in English locale and navigate to fonts.google.com – the website will load successfully.

**Expected behavior**
Functionality of fonts.google.com should not depend on Browser locale in use. If the underlying service expects "Axes" to be listed in certain order, the website should make sure to list them in that particular order.

**Comment by rimas-kudelis** [comment]
New fonts have been added, now the problem can be triggered by scrolling the page down, or typing a search for "Roboto".

**Comment by elipeters** [comment]
It's likely a "non-English" font playing havoc with the default text causing it to crash - I suspect Noto Serif Hong Kong Font is failing to load causing the error.

**Comment by rimas-kudelis** [comment]
@elipeters, I'm under the impression that you didn't read my initial post or top comment fully. I'm very positive that this is all due to the way the names of the "Axes" are sorted in a localized fashion in the browser, while the server expects them listed in a very specific order.

**Comment by davelab6** [comment]
@rimas-kudelis thanks for reporting this, excellent diagnosis, we are looking into it! :)

**Comment by xconsau** [comment]
I just came across this issue. As @rimas-kudelis pointed out, the issue arises with custom preview text when "Trending" is selected as sorting option. It works fine when choosing 'sort by' name, most popular or date added.

**Comment by garretrieger** [comment]
This should be fixed now, can you try again and let us know if there's still issues?

**Comment by xconsau** [comment]
It seems the issue still persists. Below is a video capture. Upon selecting anything except "Trending", it works fine. But for "Trending" sort option, the page crashes.

I also cross checked by clearing browser caches and in incognito mode of Chrome.

[screencast-fonts.google.com-2022.09.01-10_16_10.webm](https://user-images.githubusercontent.com/11784237/187833484-89f334eb-9b3f-473a-8fe1-7801bb7f024f.webm)

**Comment by rimas-kudelis** [comment]
My case (Roboto Flex messing things up) seems to work. Also, sorting by Trending (which is the default) works for me.

**Comment by garretrieger** [comment]
> It seems the issue still persists. Below is a video capture. Upon selecting anything except "Trending", it works fine. But for "Trending" sort option, the page crashes.
> 
> I also cross checked by clearing browser caches and in incognito mode of Chrome.
> 
>  screencast-fonts.google.com-2022.09.01-10_16_10.webm

In your case is the crash related to the use of Lithuanian locale in the browser? It's possible this might be a different issue. Either way we'll probably need some more details:

- What operating system are you using?
- What locale is your browser set too?
- Are there any errors in the browsers console log? If so can you post them onto this issue?

**Comment by xconsau** [comment]
I just checked and tried to reproduce the issue. Now it seems to work fine with all sorting options. The site is not crashing. I am using Windows 10, Chrome (English locale). The console has no errors right now.

**Comment by garretrieger** [comment]
Ok great.

**Comment by oliver-wahome** [comment]
I just got a similar issue but my locale browser language setting has English (United Kingdom) as the preferred language.
I'm using the Brave browser on a Linux Operating System(kali linux).
The errors on the console that appear when the site crashes are below:
**_ERROR Error: ea`NetworkError: A network error occurred.`
    at f (m=core:574:22)
    at n (m=core:587:172)
    at m=core:585:412
    at m=core:590:352
    at E.invoke (m=core:568:14)
    at Object.no (m=core:164:222)
    at E.invoke (m=core:567:481)
    at y.run (m=core:562:28)
    at m=core:588:214
    at E.Cj (m=core:568:352)
    at Object.Rj (m=core:164:105)
    at E.Cj (m=core:568:312)
    at y.Fo (m=core:563:53)
    at g (m=core:559:388)
handleError @ m=core:687_**

Whereas the warnings that appear are below:
**_- Failed to decode downloaded font: https://fonts.gstatic.com/s/blakaink/v5/AlZy_zVVtpj22Znag2cRcn35.woff2
- OTS parsing error: Unable to instantiate font face from font data._**

Every time I visit the google fonts website it will load for a few seconds then crash.
I cleared all my browsing data, cookies and other site data but GoogleFonts is still crashing.
Could someone assist on the matter?

**Comment by gslender** [comment]
still occurs... just browsing the fonts when variable crashes the site after about 2-3 scrolls down

**Comment by gslender** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/2344457/190932017-7a386ef6-e42a-4c65-995b-ee982e64d8cb.png">

**Comment by rimas-kudelis** [comment]
@gslender your problem is different, not relevant to browser locale.

**Comment by traceyjohnson** [comment]
![image](https://user-images.githubusercontent.com/59032065/192024121-580d4708-a9b3-4166-9eac-13ab53b11ea1.png)

I seem to be having an issue with the Google fonts website showing as well. Here is the console. How can I fix it?
