### ISSUE TITLE
Upgrade Calistoga

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#4692]
**Font Project Git Repo URL:**
https://github.com/SorkinType/Calistoga-Old

**Current version:**
[Version 1.005](https://fonts.google.com/specimen/Calistoga?query=cali)

**New available version:**
1.006

**Comment by emmamarichal** [comment]
@EbenSorkin, I transfer your comment here:

I updated this font today.

https://github.com/SorkinType/Calistoga

I think it is also ready like Pinyon but for some odd reason that I can't
seem to discover the badges are broken.

Should I try remaking this from the first steps or are the badges to needed
for bring this to GF sandbox?

**Comment by emmamarichal** [comment]
@EbenSorkin
Your link doesn't work, is it this repo: [https://github.com/SorkinType/Calistoga-Old]( https://github.com/SorkinType/Calistoga-Old) ?

If yes, I checked quickly the sources and fonts, but it's still the version 1.005, as the one we have on GF. 
I can change that to 1.006, but can you list what the upgrade brings to the font please?

**Comment by EbenSorkin** [comment]
Oh! It should be version 1.007

I checked and the source just now and that's what it says.

Is it possible you are looking at an older repo or branch? Maybe not 'main'?

[image: image.png]

As per the 'readme' there the changes are

- MAJOR Font turned to a variable font.
- SIGNIFICANT Language support improved. Additional symbols added.
- SIGNIFICANT Kerning improved.

**Comment by emmamarichal** [comment]
Hi @EbenSorkin!

I found 2 repos:
https://github.com/EbenSorkin/Calistoga
https://github.com/SorkinType/Calistoga-Old

In both cases, when I open the sources, or when I look at the version of the .ttfs, it's the 1.005 version.
Where did you put/see the 1.007 version?

Or maybe you're talking about this one: https://github.com/SorkinType/Calistoga, in that case, I can't open it (error 404).

I think we have to many repos of Calistoga haha

**Comment by EbenSorkin** [comment]
Hi Emma!

The current repo is here:

https://github.com/SorkinType/Calistoga

I checked it and found some anchor errors in a few letters and diacritics
that I fixed. I also found some easy additions to the glyph set for
improved language coverage so I added those.

I update this to 1.008

The language data in the read me isn't updated yet though.

I can delete the other repos if that would be useful. Would it be useful?

-e.

**Comment by emmamarichal** [comment]
Thanks for the update!

Don't worry for the others repos, I will link the good one to this issue and that's it! 
However, I still can't open it, it's probably in private. Can you make it public? 
Thank you!

**Comment by EbenSorkin** [comment]
Wow, do I feel silly! I thought it was.

Do you need me to update the language count info data in the read me or
anything else?

**Comment by emmamarichal** [comment]
Don't worry, thanks a lot! 
I think it should be ok on my side, if I have any problem, I'll ask you, thanks!
