### ISSUE TITLE
Khand font - wrong letter

### ISSUE THREAD

**Issue by MaRmARk0** [google/fonts#578]
Hello. I have just noticed that Khand font (https://fonts.google.com/specimen/Khand) does have an issue with capital letter Í. I always get capital É instead of Í. 

Screenshot of Khand font page. As you can see typed words "VÍCE více" resulted in "V**É**CE více".
![screenshot](http://i.imgur.com/AVBR39i.png)

Tested in Chrome 55.0.2883.87 and Firefox 50.1.0 - same results.

**Comment by davelab6** [comment]
@MaRmARk0 thanks for reporting this. I expect to get this fixed soon. cc @lianghai @itfoundry

**Comment by lianghai** [comment]
Known: https://github.com/itfoundry/khand/issues/2
Plan to resolve this issue within 2 weeks.

**Comment by kolejakjozef** [comment]
Issue still not resolved. Can you please fix it?

**Comment by laerm0** [comment]
According to the issue mentioned above on ITF's github, this is now fixed on their end. I checked out the files and it is fixed, so we should update.

**Comment by melcak** [comment]
Hi, problem is still there. I've tried download whole google fonts and generate webfont on my own, but "É" is still there instead of "Í". Can be fixed this, please? It takes months from first report. I mailed this few times throught Google Font Feedback submission, but after months problem remains. Thanks!

**Comment by chrysos** [comment]
O problema permanece... É uma pena, gostaria muito de usar esta belíssima fonte em um projeto, mas os títulos são letras maiúsculas, e o Í continua É... https://fonts.google.com/specimen/Khand

**Comment by lianghai** [comment]
@davelab6 @laerm0

Mmm… I only came to notice the issue is not reproducible in the latest https://github.com/itfoundry/khand/releases/tag/v2.000 files when I had already started upgrading the build system to the latest (so I can rebuild the family).

Anyway, the repo has been upgraded to use HindKit now (https://github.com/itfoundry/khand/tree/develop — the test build has serious interpolation issues though), so I can quickly introduce fixes anytime. Let me know if there's anything I need to do.

**Comment by gravadesign** [comment]
https://github.com/itfoundry/khand/issues/5#issue-1159411754

**Comment by yanone** [comment]
Duplicate of https://github.com/google/fonts/issues/131.
This is currently being addressed. Updated fonts should be live in around 2 weeks from now
