### ISSUE TITLE
when you print a document that written by font noto sans sc, the Chinese character will display wrong.

### ISSUE THREAD

**Issue by SayCloud** [google/fonts#6223]
For example. the document looks like bellow.
![PPT](https://user-images.githubusercontent.com/59239741/234491078-e7a6bdf6-3e56-4f4e-93a5-8db55f8cf6c0.png)

when you print it, it will show as below.
![printed](https://user-images.githubusercontent.com/59239741/234491291-9ebe9a2a-8f4e-4806-8081-aba74b5625bf.png)

you can test by PDF printer as well. same issue.
Tested NOTO SANS SC version 1. works fine.
any questions, please let me know it. appreciate your helps.
Warm Regards
Jun

**Comment by RosaWagner** [comment]
Hi @SayCloud, thanks for your report. You can file bug report in the Noto CJK repository directly: https://github.com/notofonts/noto-cjk. You may want to try with the last release in that repo, maybe the problem is already fixed but not reflected in GF API yet.

**Comment by SayCloud** [comment]
Hi, @RosaWagner Appreciate your response, I will submit the bug report, seems the issue persists now.

**Comment by aaronbell** [comment]
It appears this bug has been resolved. Closing.
